var countErrReq = 0;
var constAcl = {
    "errorMsg": "Lỗi hệ thống, vui lòng thử lại sau!",
    "API_URL": "http://app.htaviet.com:8088",
    "ws": 'ws://app.htaviet.com:6789/deviceState/',
    "REFRESH_TOKEN": 5,
    "USER_INVALID": 416,
    "CONTROL_ONLINE": false,
    "item_exits": 415,
    "not_permission_device": 410,
    "supper_admin": "supper_admin",
    "config_view": "config_view",
    "config_manage": "config_manage",
    "role_view": "role_view",
    "role_manage": "role_manage",
    "user_view": "user_view",
    "user_manage": "user_manage",
    "device_view": "device_view",
    "device_manage": "device_manage",
    "device_control": "device_control",
    "irr_view": "irr_view",
    "irr_manage": "irr_manage",
    "irr_history": "irr_history",
    "area_view": "area_view",
    "area_manage": "area_manage",
};